[build]
# Default target for cargo build
# target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=-s"]

[alias]
wasm = "build --target wasm32-unknown-unknown --release"
